// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0F1_OCwA1M7tc73tGHvUt5NsMsUvfm8w',
    appId: '1:14547264588:web:8e47c869cdfcd6fd6940e9',
    messagingSenderId: '14547264588',
    projectId: 'historyglobe-504bf',
    authDomain: 'historyglobe-504bf.firebaseapp.com',
    storageBucket: 'historyglobe-504bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAt8QYgrGL_PO8zO4bN1keUqRos_l1ZGk',
    appId: '1:14547264588:android:ad60ced08bf851376940e9',
    messagingSenderId: '14547264588',
    projectId: 'historyglobe-504bf',
    storageBucket: 'historyglobe-504bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAROwDPFm4VFB9Nzh_0yOwAZMywKZe2HGE',
    appId: '1:14547264588:ios:2e98c8905fdf01ae6940e9',
    messagingSenderId: '14547264588',
    projectId: 'historyglobe-504bf',
    storageBucket: 'historyglobe-504bf.firebasestorage.app',
    iosBundleId: 'com.example.historyGlobe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAROwDPFm4VFB9Nzh_0yOwAZMywKZe2HGE',
    appId: '1:14547264588:ios:2e98c8905fdf01ae6940e9',
    messagingSenderId: '14547264588',
    projectId: 'historyglobe-504bf',
    storageBucket: 'historyglobe-504bf.firebasestorage.app',
    iosBundleId: 'com.example.historyGlobe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0F1_OCwA1M7tc73tGHvUt5NsMsUvfm8w',
    appId: '1:14547264588:web:959a895bbb9596856940e9',
    messagingSenderId: '14547264588',
    projectId: 'historyglobe-504bf',
    authDomain: 'historyglobe-504bf.firebaseapp.com',
    storageBucket: 'historyglobe-504bf.firebasestorage.app',
  );
}
